"""initial schema

Revision ID: 335660d7aeff
Revises: 
Create Date: 2026-06-30 20:32:01.944792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '335660d7aeff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_types',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_types_code'), 'configuration_types', ['code'], unique=True)
    op.create_index(op.f('ix_configuration_types_id'), 'configuration_types', ['id'], unique=False)
    op.create_index(op.f('ix_configuration_types_is_active'), 'configuration_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_configuration_types_name'), 'configuration_types', ['name'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_is_active'), 'countries', ['is_active'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.create_table('industries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_code'), 'industries', ['code'], unique=True)
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_is_active'), 'industries', ['is_active'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('risk_classifications',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_classifications_code'), 'risk_classifications', ['code'], unique=True)
    op.create_index(op.f('ix_risk_classifications_id'), 'risk_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_risk_classifications_name'), 'risk_classifications', ['name'], unique=False)
    op.create_index(op.f('ix_risk_classifications_sort_order'), 'risk_classifications', ['sort_order'], unique=False)
    op.create_table('authorities',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_authorities_country_id_name')
    )
    op.create_index(op.f('ix_authorities_abbreviation'), 'authorities', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_authorities_country_id'), 'authorities', ['country_id'], unique=False)
    op.create_index(op.f('ix_authorities_id'), 'authorities', ['id'], unique=False)
    op.create_index(op.f('ix_authorities_is_active'), 'authorities', ['is_active'], unique=False)
    op.create_index(op.f('ix_authorities_name'), 'authorities', ['name'], unique=False)
    op.create_table('configuration_profiles',
    sa.Column('configuration_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['configuration_type_id'], ['configuration_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_type_id', 'code', 'version', name='uq_configuration_profiles_type_code_version')
    )
    op.create_index(op.f('ix_configuration_profiles_code'), 'configuration_profiles', ['code'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_configuration_type_id'), 'configuration_profiles', ['configuration_type_id'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_id'), 'configuration_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_is_active'), 'configuration_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_name'), 'configuration_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_profiles_version'), 'configuration_profiles', ['version'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('products',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('intended_use', sa.Text(), nullable=False),
    sa.Column('regulation_type', sa.Enum('IVD', 'NON_IVD', name='regulationtype'), nullable=False),
    sa.Column('risk_classification', sa.Enum('CLASS_I', 'CLASS_II', 'CLASS_III', 'CLASS_IV', name='riskclassification'), nullable=True),
    sa.Column('model_numbers', sa.JSON(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_project_id'), 'products', ['project_id'], unique=False)
    op.create_index(op.f('ix_products_regulation_type'), 'products', ['regulation_type'], unique=False)
    op.create_index(op.f('ix_products_risk_classification'), 'products', ['risk_classification'], unique=False)
    op.create_table('regulations',
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='regulationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority_id', 'code', 'version', name='uq_regulations_authority_code_version')
    )
    op.create_index(op.f('ix_regulations_authority_id'), 'regulations', ['authority_id'], unique=False)
    op.create_index(op.f('ix_regulations_code'), 'regulations', ['code'], unique=False)
    op.create_index(op.f('ix_regulations_id'), 'regulations', ['id'], unique=False)
    op.create_index(op.f('ix_regulations_industry_id'), 'regulations', ['industry_id'], unique=False)
    op.create_index(op.f('ix_regulations_name'), 'regulations', ['name'], unique=False)
    op.create_index(op.f('ix_regulations_status'), 'regulations', ['status'], unique=False)
    op.create_table('submission_types',
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_prefix', sa.String(length=50), nullable=True),
    sa.Column('allows_multiple_sequences', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_id', 'code', name='uq_submission_types_regulation_id_code')
    )
    op.create_index(op.f('ix_submission_types_code'), 'submission_types', ['code'], unique=False)
    op.create_index(op.f('ix_submission_types_id'), 'submission_types', ['id'], unique=False)
    op.create_index(op.f('ix_submission_types_is_active'), 'submission_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_submission_types_name'), 'submission_types', ['name'], unique=False)
    op.create_index(op.f('ix_submission_types_regulation_id'), 'submission_types', ['regulation_id'], unique=False)
    op.create_table('submission_profiles',
    sa.Column('submission_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('export_profile_id', sa.UUID(), nullable=True),
    sa.Column('workflow_profile_id', sa.UUID(), nullable=True),
    sa.Column('validation_profile_id', sa.UUID(), nullable=True),
    sa.Column('ai_pipeline_profile_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ai_pipeline_profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['export_profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_type_id'], ['submission_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_profile_id'], ['configuration_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_type_id', 'code', name='uq_submission_profiles_type_code')
    )
    op.create_index(op.f('ix_submission_profiles_ai_pipeline_profile_id'), 'submission_profiles', ['ai_pipeline_profile_id'], unique=False)
    op.create_index(op.f('ix_submission_profiles_code'), 'submission_profiles', ['code'], unique=False)
    op.create_index(op.f('ix_submission_profiles_export_profile_id'), 'submission_profiles', ['export_profile_id'], unique=False)
    op.create_index(op.f('ix_submission_profiles_id'), 'submission_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_submission_profiles_is_active'), 'submission_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_submission_profiles_name'), 'submission_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_submission_profiles_submission_type_id'), 'submission_profiles', ['submission_type_id'], unique=False)
    op.create_index(op.f('ix_submission_profiles_validation_profile_id'), 'submission_profiles', ['validation_profile_id'], unique=False)
    op.create_index(op.f('ix_submission_profiles_workflow_profile_id'), 'submission_profiles', ['workflow_profile_id'], unique=False)
    op.create_table('submission_type_risk_class',
    sa.Column('submission_type_id', sa.UUID(), nullable=False),
    sa.Column('risk_classification_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['risk_classification_id'], ['risk_classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_type_id'], ['submission_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_type_id', 'risk_classification_id')
    )
    op.create_table('template_versions',
    sa.Column('submission_profile_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='templatestatus'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['submission_profile_id'], ['submission_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_profile_id', 'version', name='uq_template_versions_profile_version')
    )
    op.create_index(op.f('ix_template_versions_id'), 'template_versions', ['id'], unique=False)
    op.create_index(op.f('ix_template_versions_is_latest'), 'template_versions', ['is_latest'], unique=False)
    op.create_index(op.f('ix_template_versions_status'), 'template_versions', ['status'], unique=False)
    op.create_index(op.f('ix_template_versions_submission_profile_id'), 'template_versions', ['submission_profile_id'], unique=False)
    op.create_index(op.f('ix_template_versions_version'), 'template_versions', ['version'], unique=False)
    op.create_table('required_documents',
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('allowed_extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_mime_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('minimum_files', sa.Integer(), nullable=False),
    sa.Column('maximum_files', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'name', name='uq_required_documents_version_name')
    )
    op.create_index(op.f('ix_required_documents_id'), 'required_documents', ['id'], unique=False)
    op.create_index(op.f('ix_required_documents_name'), 'required_documents', ['name'], unique=False)
    op.create_index(op.f('ix_required_documents_required'), 'required_documents', ['required'], unique=False)
    op.create_index(op.f('ix_required_documents_template_version_id'), 'required_documents', ['template_version_id'], unique=False)
    op.create_table('submissions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('submission_profile_id', sa.UUID(), nullable=True),
    sa.Column('template_version_id', sa.UUID(), nullable=True),
    sa.Column('sequence_number', sa.String(length=32), nullable=False),
    sa.Column('submission_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AI_PROCESSING', 'HUMAN_REVIEW', 'APPROVED', 'SUBMITTED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('health_canada_reference', sa.String(length=255), nullable=True),
    sa.Column('target_submission_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submission_profile_id'], ['submission_profiles.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sequence_number', name='uq_submissions_product_id_sequence_number')
    )
    op.create_index(op.f('ix_submissions_health_canada_reference'), 'submissions', ['health_canada_reference'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_organization_id'), 'submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_submissions_product_id'), 'submissions', ['product_id'], unique=False)
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_submissions_sequence_number'), 'submissions', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submission_profile_id'), 'submissions', ['submission_profile_id'], unique=False)
    op.create_index(op.f('ix_submissions_template_version_id'), 'submissions', ['template_version_id'], unique=False)
    op.create_table('template_sections',
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['template_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'section_number', name='uq_template_sections_version_section_number')
    )
    op.create_index(op.f('ix_template_sections_id'), 'template_sections', ['id'], unique=False)
    op.create_index(op.f('ix_template_sections_is_required'), 'template_sections', ['is_required'], unique=False)
    op.create_index(op.f('ix_template_sections_parent_id'), 'template_sections', ['parent_id'], unique=False)
    op.create_index(op.f('ix_template_sections_section_number'), 'template_sections', ['section_number'], unique=False)
    op.create_index(op.f('ix_template_sections_template_version_id'), 'template_sections', ['template_version_id'], unique=False)
    op.create_table('validation_rules',
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('DOCUMENT', 'SECTION', 'SUBMISSION', name='validationtargettype'), nullable=False),
    sa.Column('target_reference', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_expression', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='validationseverity'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_validation_rules_is_active'), 'validation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_validation_rules_rule_type'), 'validation_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_validation_rules_severity'), 'validation_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_rules_target_reference'), 'validation_rules', ['target_reference'], unique=False)
    op.create_index(op.f('ix_validation_rules_target_type'), 'validation_rules', ['target_type'], unique=False)
    op.create_index(op.f('ix_validation_rules_template_version_id'), 'validation_rules', ['template_version_id'], unique=False)
    op.create_table('consistency_checks',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_sections', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_checks_check_type'), 'consistency_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_consistency_checks_id'), 'consistency_checks', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_checks_is_resolved'), 'consistency_checks', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_consistency_checks_severity'), 'consistency_checks', ['severity'], unique=False)
    op.create_index(op.f('ix_consistency_checks_submission_id'), 'consistency_checks', ['submission_id'], unique=False)
    op.create_table('section_rules',
    sa.Column('template_section_id', sa.UUID(), nullable=False),
    sa.Column('required_document_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['required_document_id'], ['required_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_section_id'], ['template_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_section_id', 'required_document_id', 'rule_type', name='uq_section_rules_section_document_rule_type')
    )
    op.create_index(op.f('ix_section_rules_id'), 'section_rules', ['id'], unique=False)
    op.create_index(op.f('ix_section_rules_required_document_id'), 'section_rules', ['required_document_id'], unique=False)
    op.create_index(op.f('ix_section_rules_rule_type'), 'section_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_section_rules_template_section_id'), 'section_rules', ['template_section_id'], unique=False)
    op.create_table('submission_documents',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('required_document_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['required_document_id'], ['required_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_documents_id'), 'submission_documents', ['id'], unique=False)
    op.create_index(op.f('ix_submission_documents_required_document_id'), 'submission_documents', ['required_document_id'], unique=False)
    op.create_index(op.f('ix_submission_documents_status'), 'submission_documents', ['status'], unique=False)
    op.create_index(op.f('ix_submission_documents_submission_id'), 'submission_documents', ['submission_id'], unique=False)
    op.create_table('submission_validation_items',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('validation_rule_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_reference', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_rule_id'], ['validation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_validation_items_id'), 'submission_validation_items', ['id'], unique=False)
    op.create_index(op.f('ix_submission_validation_items_status'), 'submission_validation_items', ['status'], unique=False)
    op.create_index(op.f('ix_submission_validation_items_submission_id'), 'submission_validation_items', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submission_validation_items_validation_rule_id'), 'submission_validation_items', ['validation_rule_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'XLSX', 'OTHER', name='filetype'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('upload_purpose', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_uploaded_files_file_type'), 'uploaded_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_is_processed'), 'uploaded_files', ['is_processed'], unique=False)
    op.create_index(op.f('ix_uploaded_files_product_id'), 'uploaded_files', ['product_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_project_id'), 'uploaded_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_submission_id'), 'uploaded_files', ['submission_id'], unique=False)
    op.create_table('dossier_sections',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('section_description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('template_source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placeholder_content', sa.Text(), nullable=True),
    sa.Column('ai_extracted_content', sa.Text(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('conflict_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_sections_has_conflicts'), 'dossier_sections', ['has_conflicts'], unique=False)
    op.create_index(op.f('ix_dossier_sections_id'), 'dossier_sections', ['id'], unique=False)
    op.create_index(op.f('ix_dossier_sections_is_completed'), 'dossier_sections', ['is_completed'], unique=False)
    op.create_index(op.f('ix_dossier_sections_parent_section_id'), 'dossier_sections', ['parent_section_id'], unique=False)
    op.create_index(op.f('ix_dossier_sections_section_code'), 'dossier_sections', ['section_code'], unique=False)
    op.create_index(op.f('ix_dossier_sections_submission_id'), 'dossier_sections', ['submission_id'], unique=False)
    op.create_table('extracted_content',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_content_file_id'), 'extracted_content', ['file_id'], unique=False)
    op.create_index(op.f('ix_extracted_content_id'), 'extracted_content', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_content_reviewed'), 'extracted_content', ['reviewed'], unique=False)
    op.create_table('human_reviews',
    sa.Column('reviewable_type', sa.Enum('DOSSIER_SECTION', 'SUBMISSION', 'EXTRACTED_CONTENT', name='reviewabletype'), nullable=False),
    sa.Column('reviewable_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='reviewstatus'), nullable=False),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('suggested_changes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('dossier_section_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('extracted_content_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['extracted_content_id'], ['extracted_content.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_dossier_section_id'), 'human_reviews', ['dossier_section_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_extracted_content_id'), 'human_reviews', ['extracted_content_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_id'), 'human_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_human_reviews_review_status'), 'human_reviews', ['review_status'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewable_id'), 'human_reviews', ['reviewable_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewable_type'), 'human_reviews', ['reviewable_type'], unique=False)
    op.create_index(op.f('ix_human_reviews_submission_id'), 'human_reviews', ['submission_id'], unique=False)
    op.create_table('missing_content',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('dossier_section_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('MISSING_SECTION', 'INCOMPLETE_CONTENT', 'MISSING_FILE', name='alerttype'), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_content_alert_type'), 'missing_content', ['alert_type'], unique=False)
    op.create_index(op.f('ix_missing_content_dossier_section_id'), 'missing_content', ['dossier_section_id'], unique=False)
    op.create_index(op.f('ix_missing_content_id'), 'missing_content', ['id'], unique=False)
    op.create_index(op.f('ix_missing_content_is_resolved'), 'missing_content', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_missing_content_severity'), 'missing_content', ['severity'], unique=False)
    op.create_index(op.f('ix_missing_content_submission_id'), 'missing_content', ['submission_id'], unique=False)
    op.create_table('section_content_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_section_id', sa.UUID(), nullable=False),
    sa.Column('extracted_content_id', sa.UUID(), nullable=False),
    sa.Column('is_primary_content', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('mapped_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['extracted_content_id'], ['extracted_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_content_map')
    op.drop_index(op.f('ix_missing_content_submission_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_severity'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_is_resolved'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_dossier_section_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_alert_type'), table_name='missing_content')
    op.drop_table('missing_content')
    op.drop_index(op.f('ix_human_reviews_submission_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reviewable_type'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reviewable_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_review_status'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_extracted_content_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_dossier_section_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_extracted_content_reviewed'), table_name='extracted_content')
    op.drop_index(op.f('ix_extracted_content_id'), table_name='extracted_content')
    op.drop_index(op.f('ix_extracted_content_file_id'), table_name='extracted_content')
    op.drop_table('extracted_content')
    op.drop_index(op.f('ix_dossier_sections_submission_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_section_code'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_parent_section_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_is_completed'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_has_conflicts'), table_name='dossier_sections')
    op.drop_table('dossier_sections')
    op.drop_index(op.f('ix_uploaded_files_submission_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_project_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_product_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_is_processed'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_type'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_submission_validation_items_validation_rule_id'), table_name='submission_validation_items')
    op.drop_index(op.f('ix_submission_validation_items_submission_id'), table_name='submission_validation_items')
    op.drop_index(op.f('ix_submission_validation_items_status'), table_name='submission_validation_items')
    op.drop_index(op.f('ix_submission_validation_items_id'), table_name='submission_validation_items')
    op.drop_table('submission_validation_items')
    op.drop_index(op.f('ix_submission_documents_submission_id'), table_name='submission_documents')
    op.drop_index(op.f('ix_submission_documents_status'), table_name='submission_documents')
    op.drop_index(op.f('ix_submission_documents_required_document_id'), table_name='submission_documents')
    op.drop_index(op.f('ix_submission_documents_id'), table_name='submission_documents')
    op.drop_table('submission_documents')
    op.drop_index(op.f('ix_section_rules_template_section_id'), table_name='section_rules')
    op.drop_index(op.f('ix_section_rules_rule_type'), table_name='section_rules')
    op.drop_index(op.f('ix_section_rules_required_document_id'), table_name='section_rules')
    op.drop_index(op.f('ix_section_rules_id'), table_name='section_rules')
    op.drop_table('section_rules')
    op.drop_index(op.f('ix_consistency_checks_submission_id'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_severity'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_is_resolved'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_id'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_check_type'), table_name='consistency_checks')
    op.drop_table('consistency_checks')
    op.drop_index(op.f('ix_validation_rules_template_version_id'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_target_type'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_target_reference'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_severity'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_rule_type'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_is_active'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_template_sections_template_version_id'), table_name='template_sections')
    op.drop_index(op.f('ix_template_sections_section_number'), table_name='template_sections')
    op.drop_index(op.f('ix_template_sections_parent_id'), table_name='template_sections')
    op.drop_index(op.f('ix_template_sections_is_required'), table_name='template_sections')
    op.drop_index(op.f('ix_template_sections_id'), table_name='template_sections')
    op.drop_table('template_sections')
    op.drop_index(op.f('ix_submissions_template_version_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submission_profile_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_sequence_number'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_project_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_product_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_organization_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_health_canada_reference'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_required_documents_template_version_id'), table_name='required_documents')
    op.drop_index(op.f('ix_required_documents_required'), table_name='required_documents')
    op.drop_index(op.f('ix_required_documents_name'), table_name='required_documents')
    op.drop_index(op.f('ix_required_documents_id'), table_name='required_documents')
    op.drop_table('required_documents')
    op.drop_index(op.f('ix_template_versions_version'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_submission_profile_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_status'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_is_latest'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_table('submission_type_risk_class')
    op.drop_index(op.f('ix_submission_profiles_workflow_profile_id'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_validation_profile_id'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_submission_type_id'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_name'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_is_active'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_id'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_export_profile_id'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_code'), table_name='submission_profiles')
    op.drop_index(op.f('ix_submission_profiles_ai_pipeline_profile_id'), table_name='submission_profiles')
    op.drop_table('submission_profiles')
    op.drop_index(op.f('ix_submission_types_regulation_id'), table_name='submission_types')
    op.drop_index(op.f('ix_submission_types_name'), table_name='submission_types')
    op.drop_index(op.f('ix_submission_types_is_active'), table_name='submission_types')
    op.drop_index(op.f('ix_submission_types_id'), table_name='submission_types')
    op.drop_index(op.f('ix_submission_types_code'), table_name='submission_types')
    op.drop_table('submission_types')
    op.drop_index(op.f('ix_regulations_status'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_name'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_industry_id'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_id'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_code'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_authority_id'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_products_risk_classification'), table_name='products')
    op.drop_index(op.f('ix_products_regulation_type'), table_name='products')
    op.drop_index(op.f('ix_products_project_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_configuration_profiles_version'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_name'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_is_active'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_id'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_configuration_type_id'), table_name='configuration_profiles')
    op.drop_index(op.f('ix_configuration_profiles_code'), table_name='configuration_profiles')
    op.drop_table('configuration_profiles')
    op.drop_index(op.f('ix_authorities_name'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_is_active'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_id'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_country_id'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_abbreviation'), table_name='authorities')
    op.drop_table('authorities')
    op.drop_index(op.f('ix_risk_classifications_sort_order'), table_name='risk_classifications')
    op.drop_index(op.f('ix_risk_classifications_name'), table_name='risk_classifications')
    op.drop_index(op.f('ix_risk_classifications_id'), table_name='risk_classifications')
    op.drop_index(op.f('ix_risk_classifications_code'), table_name='risk_classifications')
    op.drop_table('risk_classifications')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_is_active'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_code'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_is_active'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_configuration_types_name'), table_name='configuration_types')
    op.drop_index(op.f('ix_configuration_types_is_active'), table_name='configuration_types')
    op.drop_index(op.f('ix_configuration_types_id'), table_name='configuration_types')
    op.drop_index(op.f('ix_configuration_types_code'), table_name='configuration_types')
    op.drop_table('configuration_types')
    # ### end Alembic commands ###