"""initial_schema

Revision ID: ce76cc308471
Revises: 
Create Date: 2026-06-24 12:15:25.610871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce76cc308471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('products',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('intended_use', sa.Text(), nullable=False),
    sa.Column('regulation_type', sa.Enum('IVD', 'NON_IVD', name='regulationtype'), nullable=False),
    sa.Column('risk_classification', sa.Enum('CLASS_I', 'CLASS_II', 'CLASS_III', 'CLASS_IV', name='riskclassification'), nullable=True),
    sa.Column('model_numbers', sa.JSON(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_project_id'), 'products', ['project_id'], unique=False)
    op.create_index(op.f('ix_products_regulation_type'), 'products', ['regulation_type'], unique=False)
    op.create_index(op.f('ix_products_risk_classification'), 'products', ['risk_classification'], unique=False)
    op.create_table('submissions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('submission_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AI_PROCESSING', 'HUMAN_REVIEW', 'APPROVED', 'SUBMITTED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('health_canada_reference', sa.String(length=255), nullable=True),
    sa.Column('target_submission_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_health_canada_reference'), 'submissions', ['health_canada_reference'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_name'), 'submissions', ['name'], unique=False)
    op.create_index(op.f('ix_submissions_organization_id'), 'submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_submissions_product_id'), 'submissions', ['product_id'], unique=False)
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('consistency_checks',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_sections', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_checks_check_type'), 'consistency_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_consistency_checks_id'), 'consistency_checks', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_checks_is_resolved'), 'consistency_checks', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_consistency_checks_severity'), 'consistency_checks', ['severity'], unique=False)
    op.create_index(op.f('ix_consistency_checks_submission_id'), 'consistency_checks', ['submission_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'XLSX', 'OTHER', name='filetype'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('upload_purpose', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_uploaded_files_file_type'), 'uploaded_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_is_processed'), 'uploaded_files', ['is_processed'], unique=False)
    op.create_index(op.f('ix_uploaded_files_project_id'), 'uploaded_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_submission_id'), 'uploaded_files', ['submission_id'], unique=False)
    op.create_table('dossier_sections',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('section_description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('template_source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placeholder_content', sa.Text(), nullable=True),
    sa.Column('ai_extracted_content', sa.Text(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('conflict_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_sections_has_conflicts'), 'dossier_sections', ['has_conflicts'], unique=False)
    op.create_index(op.f('ix_dossier_sections_id'), 'dossier_sections', ['id'], unique=False)
    op.create_index(op.f('ix_dossier_sections_is_completed'), 'dossier_sections', ['is_completed'], unique=False)
    op.create_index(op.f('ix_dossier_sections_parent_section_id'), 'dossier_sections', ['parent_section_id'], unique=False)
    op.create_index(op.f('ix_dossier_sections_section_code'), 'dossier_sections', ['section_code'], unique=False)
    op.create_index(op.f('ix_dossier_sections_submission_id'), 'dossier_sections', ['submission_id'], unique=False)
    op.create_table('extracted_content',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=255), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_content_file_id'), 'extracted_content', ['file_id'], unique=False)
    op.create_index(op.f('ix_extracted_content_id'), 'extracted_content', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_content_reviewed'), 'extracted_content', ['reviewed'], unique=False)
    op.create_table('human_reviews',
    sa.Column('reviewable_type', sa.Enum('DOSSIER_SECTION', 'SUBMISSION', 'EXTRACTED_CONTENT', name='reviewabletype'), nullable=False),
    sa.Column('reviewable_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='reviewstatus'), nullable=False),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('suggested_changes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('dossier_section_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('extracted_content_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['extracted_content_id'], ['extracted_content.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_dossier_section_id'), 'human_reviews', ['dossier_section_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_extracted_content_id'), 'human_reviews', ['extracted_content_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_id'), 'human_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_human_reviews_review_status'), 'human_reviews', ['review_status'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewable_id'), 'human_reviews', ['reviewable_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewable_type'), 'human_reviews', ['reviewable_type'], unique=False)
    op.create_index(op.f('ix_human_reviews_submission_id'), 'human_reviews', ['submission_id'], unique=False)
    op.create_table('missing_content',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('dossier_section_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('MISSING_SECTION', 'INCOMPLETE_CONTENT', 'MISSING_FILE', name='alerttype'), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_content_alert_type'), 'missing_content', ['alert_type'], unique=False)
    op.create_index(op.f('ix_missing_content_dossier_section_id'), 'missing_content', ['dossier_section_id'], unique=False)
    op.create_index(op.f('ix_missing_content_id'), 'missing_content', ['id'], unique=False)
    op.create_index(op.f('ix_missing_content_is_resolved'), 'missing_content', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_missing_content_severity'), 'missing_content', ['severity'], unique=False)
    op.create_index(op.f('ix_missing_content_submission_id'), 'missing_content', ['submission_id'], unique=False)
    op.create_table('section_content_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_section_id', sa.UUID(), nullable=False),
    sa.Column('extracted_content_id', sa.UUID(), nullable=False),
    sa.Column('is_primary_content', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('mapped_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_section_id'], ['dossier_sections.id'], ),
    sa.ForeignKeyConstraint(['extracted_content_id'], ['extracted_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_content_map')
    op.drop_index(op.f('ix_missing_content_submission_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_severity'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_is_resolved'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_dossier_section_id'), table_name='missing_content')
    op.drop_index(op.f('ix_missing_content_alert_type'), table_name='missing_content')
    op.drop_table('missing_content')
    op.drop_index(op.f('ix_human_reviews_submission_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reviewable_type'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reviewable_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_review_status'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_extracted_content_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_dossier_section_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_extracted_content_reviewed'), table_name='extracted_content')
    op.drop_index(op.f('ix_extracted_content_id'), table_name='extracted_content')
    op.drop_index(op.f('ix_extracted_content_file_id'), table_name='extracted_content')
    op.drop_table('extracted_content')
    op.drop_index(op.f('ix_dossier_sections_submission_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_section_code'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_parent_section_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_is_completed'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_id'), table_name='dossier_sections')
    op.drop_index(op.f('ix_dossier_sections_has_conflicts'), table_name='dossier_sections')
    op.drop_table('dossier_sections')
    op.drop_index(op.f('ix_uploaded_files_submission_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_project_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_is_processed'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_type'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_consistency_checks_submission_id'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_severity'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_is_resolved'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_id'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_check_type'), table_name='consistency_checks')
    op.drop_table('consistency_checks')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_project_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_product_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_organization_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_name'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_health_canada_reference'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_products_risk_classification'), table_name='products')
    op.drop_index(op.f('ix_products_regulation_type'), table_name='products')
    op.drop_index(op.f('ix_products_project_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###